x = input('Digite qualquer coisa:')
print('E alfanumerico? ', x.isalnum())
print('E alfabetico? ', x.isalpha())
print('E ASCII? ', x.isascii())
print('E numero? ', x.isdigit())
print('Esta em minusculas? ', x.islower())
print('E decimal? ', x.isdecimal())
print('E identificador? ', x.isidentifier())
print('E numerico? ', x.isnumeric())
print('E imprimivel? ', x.isprintable())
print('E espaco? ', x.isspace())
print('E titulo? ', x.istitle())
print('Esta em maiusculas? ', x.isupper())
